name: Trigger build

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Kiểm tra commit message
      - name: Check commit message
        id: check_commit
        run: |
          echo "Checking last commit message..."
          if [[ "${{ github.event.head_commit.message }}" == "Trigger Build" ]]; then
            echo "SKIP_TRIGGER=true" >> $GITHUB_ENV
            echo "Skipping trigger as this is already a trigger commit"
          else
            echo "SKIP_TRIGGER=false" >> $GITHUB_ENV
          fi

      # Chỉ tiếp tục nếu không phải commit "Trigger Build"
      - uses: actions/checkout@v3
        if: env.SKIP_TRIGGER == 'false'
        with:
          persist-credentials: false

      # Loại bỏ bước Checkout PR vì chỉ xử lý push

      - name: Configure git user
        if: env.SKIP_TRIGGER == 'false'
        run: |
          git config user.email "vulinhtruong79@gmail.com"
          git config user.name "vulinhnopro2704"

      - name: Set remote with PAT
        if: env.SKIP_TRIGGER == 'false'
        env:
          PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}.git

      - name: Trigger build
        if: env.SKIP_TRIGGER == 'false'
        env:
          PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          git commit --allow-empty -m "Trigger Build"
          git push origin HEAD:${{ github.ref_name }}