name: Trigger build

on:
  push:
    branches: ['main', 'develop']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout PR
        if: github.event_name == 'pull_request'
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Configure git user
        run: |
          git config user.email "vulinhtruong79@gmail.com"
          git config user.name "vulinhnopro2704"

      - name: Set remote with PAT
        env:
          PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}.git

      - name: Trigger build
        env:
          PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          git commit --allow-empty -m "Trigger Build"
          git push origin HEAD:${{ github.ref_name }}
